- hosts: all
  become: yes
  roles:
    - role: config-golang
      arch: arm64
  tasks:
    - name: Build containerd
      shell:
        cmd: |
          set -xe
          apt-get update
          apt-get install -y btrfs-tools libseccomp-dev git pkg-config

          if [ ! -d "$GOPATH/src/github.com/containerd" ] ; then
            # the src is forked by openlab, so we need link the src to containerd/containerd.
            mkdir -p $GOPATH/src/github.com/containerd/
            ln -s '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}' $GOPATH/src/github.com/containerd/containerd
            cd $GOPATH/src/github.com/containerd/containerd
          fi

          make | tee $LOGS_PATH/make.txt
          make test | tee $LOGS_PATH/make_test.txt

          cp -r ./bin $RESULTS_PATH
        chdir: '{{ zuul.project.src_dir }}'
        executable: /bin/bash
      environment: '{{ global_env }}'
